version: '3'

services:
  kyrs_php:
    build: ./php
    container_name: kyrs_php
    volumes:
      - ../server:/var/www/html
    ports:
      - 8071:80
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_MEMORY_LIMIT: 1024M
      PHP_UPLOAD_MAX_FILESIZE: 512M
      PHP_POST_MAX_SIZE: 512M
      PHP_DISPLAY_ERRORS: 1
      php.xdebug.max_nesting_level: 500
    depends_on:
      - kyrs_mysql


  kyrs_mysql:
    build: ./mysql/
    container_name: kyrs_mysql
    environment:
      MYSQL_ROOT_PASSWORD: bfigf_iee-bifjb
      MYSQL_DATABASE: kyrsi
    ports:
      - 3308:3306
